# Generated by Django 4.2.7 on 2026-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выезда'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег при выезде'),
        ),
    ]
